/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/KVRC_Bot.gltf --output src/components/KVRCBot.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/KVRC_Bot.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="empty_1">
        <group name="FBX_Root">
          <primitive object={nodes.mixamorig_Hips} />
          <skinnedMesh name="LDR_Bot001" geometry={nodes.LDR_Bot001.geometry} material={materials['TT_material_override-LDR_Bot.001']} skeleton={nodes.LDR_Bot001.skeleton} position={[-1.639, -0.575, -6.443]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/KVRC_Bot.gltf')
