/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/robot_k.glb --output src/components/RobotModel.jsx 
Author: VolDeMaar (Padawan 3D) (https://sketchfab.com/Padawan3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-k-vrc-11ca2a59002b4c64986b44e46f389b47
Title: Robot K-VRC
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robot_k.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes['LDR_Bot001_TT_material_override-LDR_Bot001_0'].geometry} material={materials['TT_material_override-LDR_Bot.001']} position={[-1.639, -0.575, -6.443]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/robot_k.glb')
